name: release-native-linux-amd64
on:
  release:
    types: [ created ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install GraalVM
        uses: DeLaGuardo/setup-graalvm@4.0
        with:
          graalvm: '21.2.0'
          java: 'java11'
          arch: 'amd64'
      - name: Install GraalVM native-image
        run: gu install native-image
      - name: Build native CLI executable
        run: ./gradlew clean connekted-cli:build -x test -Dquarkus.package.type=native -Dconnekted.release.tag=${{github.event.release.tag_name}}
      - name: Upload native CLI executable
        id: upload-native-cli-executable
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{secrets.RELEASE_TOKEN}}
        with:
          upload_url: ${{github.event.release.upload_url}}
          asset_path: ./connekted-cli/build/connekted-cli-${{github.event.release.tag_name}}-runner
          asset_name: connekted-cli-${{github.event.release.tag_name}}-linux-amd64
          asset_content_type: application/octet-stream